### ISSUE TITLE
Exception throwed.

### ISSUE THREAD

**Issue by rigroch** [misterion/ko-worker#10]
Hi, 
i tried your example code, but throw exception follow that,

./ko -c ./examples/ReceiverClass/config.yaml -q user -w 1 -f 1
PHP Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Executor class \Ko\Examples\ReceiverClass\Actions\HelloWorld should implements Ko\Worker\ActionInterface' in /data/web_data/hanuri/htdocs/front_end/ko-worker/vendor/misterion/ko-worker/src/Ko/Worker/Child.php:77

AND 

./ko -c ./examples/BasicSenderReceiver/config.yaml -q user -w 1 -f 1
PHP Fatal error: Uncaught exception 'DomainException' with message 'You must declare a class for the job' in /data/web_data/hanuri/htdocs/front_end/ko-worker/vendor/misterion/ko-worker/src/Ko/Worker/Application.php:259

how do i fix it?

**Comment by webdes83** [comment]
me too

**Comment by misterion** [comment]
Currently i can`t reproduce bug with ReceiverClass sample. That version of library are you using? 

About BasicSenderReceiver example. It does not require `ko` console application as runner. It is an sample about library usage as-is without any types of runner/helper. Just run in console as `php receiver.php`.

**Comment by misterion** [comment]
No reply in 3 month.
