### ISSUE TITLE
AMQPConnection not found

### ISSUE THREAD

**Issue by umpirsky** [misterion/ko-worker#14]
I got:

```
PHP Fatal error:  Class 'AMQPConnection' not found in vendor/misterion/ko-worker/src/Ko/RabbitMq/ConnectionFactory.php on line 86
```

using latest master branch.

Looks like I am missing ext-amqp, consider moving it to required section.

**Comment by misterion** [comment]
Yes, `ext-amqp` missing on your system. Composer have `--ignore-platform-reqs` but in most of cases, i think, keep this requirement in suggested may be more usable.

**Comment by umpirsky** [comment]
@misterion So, this library cannot work with [videlalvaro/php-amqplib](https://github.com/videlalvaro/php-amqplib)?

**Comment by misterion** [comment]
No, currently it work with native AMQP php library. videlalvaro/php-amqplib nice library but perfomance it perfomance is low. We use ko-worker in high load production so do not write any code to use some abstraction above AMQP library. But you can write it - it is nice idea for pull request.

**Comment by umpirsky** [comment]
@misterion I see. Thanks for the feedback! :+1:
